### ISSUE TITLE
Why did we dump the .livecodescript file?

### ISSUE THREAD

**Issue by macMikey** [derbrill/libdate#13]
.livecodescript is the suffix you would use to make this into a script-only behavior stack or substack for inclusion in a project.  .script has no meaning in the livecode universe.

**Comment by derbrill** [comment]
Hi mickey,

I had to close the pull request because it caused a conflict in the master branch which I could not resolve (basically because of being clueless about git). I agree it makes sense to name the file .livecodescript and will try to do so, once git is no longer throwing conflicts at me. :-)

**Comment by macMikey** [comment]
tell me about the conflicts.

**Comment by derbrill** [comment]
Should be resolved now. :-)
